### ISSUE TITLE
Boxes on front page render vertically in IE

### ISSUE THREAD

**Issue by jonpacker** [bring/developer-site#79]
It looks like this is because of missing flexbox support. Or something. Here's a screenshot:

![skjermbilde 2015-12-08 kl 15 58 00](https://cloud.githubusercontent.com/assets/678101/11658740/7d4c3ee0-9dc4-11e5-9ba7-893c459db130.png)

**Comment by elisabethirgens** [comment]
Yeah… I’ve been pretty pragmatic here, thinking that the content is perfectly readable in all browsers — but that the users for this site (developers) are not using IE (unless testing!) 

[Support for flexbox](http://caniuse.com/#search=flexbox) is good enough to make it really interesting to play around with for components like this. But perhaps it should get a decent fallback so it looks less weird.

**Comment by jonpacker** [comment]
You might be able to solve it with a polyfill like http://flexiejs.com - but I otherwise I agree that on a developer site it really doesn't matter than much, the IE demographic is going to be absolutely tiny. Feel free to go ahead and close if you like.

**Comment by elisabethirgens** [comment]
I want to keep it open, because if flexboxing works consistently here in our “backyard” — we can start thinking about using it elsewhere. This developer site is where we can play around with newer techniques before trying to use them places where browser support matters more. 

But I’ll check that I’ve not missed something on [prefixing or old/new syntax](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) before looking at polyfills.
